`riki render`: clarify template name
This switches the template name from `template` to the template path in
order to make error messages clearer:

    Error: Error rendering "templates/default.hbs" line 15, col 35: ...

Instead of:

    Error: Error rendering "template" line 15, col 35: ...